version: "3"

services:
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root1234
      - MYSQL_DATABASE=testdb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user1234
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./logs:/logs
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
      - "--lower_case_table_names=1"
      - "--innodb_file_per_table=1"
      - "--default-storage-engine=InnoDB"
      - "--long_query_time=0.5"
      - "--skip-name-resolve=1"
      - "--slow_query_log"
      - "--slow_query_log_file=/tmp/slow.log"

